# ─── Autostart y layerrules para la barra ───
# source = ~/.config/quickshell/barra/hypr/barra.conf

exec-once = qs -p ~/.config/quickshell/barra/shell.qml
exec-once = qs -p ~/.config/quickshell/wallclock/shell.qml
exec-once = qs -p ~/.config/quickshell/calendar/shell.qml
exec-once = easyeffects --service-mode

bind = SUPER, K, global, qs-shortcuts:music-toggle

layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0, match:namespace quickshell
