# ─── Blur optimizado para vidrio empañado ───
# source = ~/.config/quickshell/barra/hypr/lookandfeel.conf
decoration {
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true
        new_optimizations = on
        vibrancy = 0.1696
    }
}
